FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./common ./common
COPY ./etl ./etl
RUN useradd -r -s /sbin/nologin appuser && chown -R appuser /app
USER appuser
ENV API_URL="http://backend:8000"

# --- AJOUTEZ CETTE LIGNE ---
ENV PYTHONPATH="${PYTHONPATH}:/app"

CMD ["python", "etl/generator.py"]