FROM python:3.10-slim
WORKDIR /app
RUN pip install --no-cache-dir streamlit pandas requests seaborn matplotlib
COPY ./frontend ./frontend
CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]