FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir fastapi uvicorn pandas scikit-learn sqlalchemy psycopg2-binary
COPY ./common ./common
COPY ./backend ./backend
RUN useradd -r -s /sbin/nologin appuser && chown -R appuser /app
USER appuser
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]